### ISSUE TITLE
`setup-dvc` fails to run

### ISSUE THREAD

**Issue by dacbd** [iterative/setup-dvc#35]
Discovered from a user's workflow in discord.

The `setup-dvc` action fails when used with the `ghcr.io/iterative/cml:0-dvc2-base1` container.
Ideally, this should never happen since dvc is provided in the container... but you know what can be done will be done 😄 

[example output:](https://github.com/dacbd/err/runs/6797859192?check_suite_focus=true)
```
jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: iterative/setup-dvc@v1
```
