### ISSUE TITLE
No module named 'dvc_gs'

### ISSUE THREAD

**Issue by nturusin** [iterative/setup-dvc#41]
Hi. The workflow below
```
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: '275.0.0'
          service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
      - name: Login
        run: gcloud auth configure-docker
      - uses: iterative/setup-dvc@v1
      - name: Fetch dvc
        run: |
          echo $GCLOUD_SERVICE_ACCOUNT_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
          dvc pull
          ...
```

"Fetch dvc" fails with the error:
```
ERROR: unexpected error - gs is supported, but requires 'dvc-gs' to be installed: No module named 'dvc_gs'
```

This worked as a charm before but not now
